spring:
  config:
    activate:
      on-profile: prod
    import:
      - 'classpath:persistence-property-prod.yml'
  data:
    redis:
      enabled: true
      host: localhost
      port: 46379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 10000ms
jwt:
  helper-enabled: true
  pre-fix:
    server: api
  access-token:
    secret-key: RFQtSW5ub3ZhdGlvbl9KV1RfVG9rZW5fU2VjcmV0S2V5 # DT-Innovation_JWT_Access_Token_SecretKey
  refresh-token:
    secret-key: RFQtSW5ub3ZhdGlvbl9KV1RfVG9rZW5fU2VjcmV0S2V5 # DT-Innovation_JWT_Refresh_Token_SecretKey


logging:
  level:
    root: info