spring:
  datasource:
    hikari:
      driver-class-name: software.aws.rds.jdbc.mysql.Driver
      jdbc-url: jdbc:mysql://localhost:53306/dtinnodb?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
      username: root
      password: root123!@#
      poolName: DtInnoDbHikariCP
      max-lifetime: 1800000 # 30 minutes
      connection-timeout: 30000 # 30 seconds
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        show-sql: false
        physical_naming_strategy: com.deutschmotors.moduledata.config.UppercaseSnakePhysicalNamingStrategy
    hibernate:
      ddl-auto: update
    generate-ddl: false
    open-in-view: false